### ISSUE TITLE
Icon version with some shading

### ISSUE THREAD

**Issue by TimboKZ** [tkoyama010/tkoyama010#6]
![Version with some shading](https://user-images.githubusercontent.com/5504588/86118668-10b96600-bac9-11ea-921b-769c64cda369.png)
[shaded.txt](https://github.com/tkoyama010/icon/files/4851303/shaded.txt)

**Comment by tkoyama010** [comment]
Thanks :laughing:

**Comment by tkoyama010** [comment]
I made a PR #9 for this issue. I'll use this Icon when I want to have shade.
